services:
    run:
        restart: unless-stopped
        container_name: ward
        ports:
            - '4000:4000'
        environment:
            - WARD_PORT=4000
            - WARD_THEME=light
            - WARD_NAME=Ward
            - WARD_FOG=true
            - WARD_BACKGROUND=#3c3c3c # disable fog to use background
        privileged: true
        image: antonyleons/ward
