name: build-jar
on: pull_request
jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: mvn clean install
      - run: mvn clean package
      - uses: actions/upload-artifact@v3
        with:
          name: Ward.jar
          path: target/*.jar