name: docker-image
on: 
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.10.0
      with:
        push: true
        platforms: linux/amd64,linux/arm64,linux/s390x
        tags: antonyleons/ward:latest,antonyleons/ward:${{GITHUB_REF#refs/tags/}}

